version: '3.9'
services:
  nest-project:
    build:
      context: .
      dockerfile: 'Dockerfile'
    env_file:
      - ./.env
    volumes:
      - test.db:/home/node/app/test.db
    ports:
      - '3000:3000'

volumes:
  test.db: